package org.ch.message.model;

import java.util.Date;

public class Calendar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.calendar_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Integer calendarSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.calendar_name
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String calendarName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.group_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Integer groupSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.removed
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String removed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.reg_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.mod_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Date modTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.calendar_seq
     *
     * @return the value of calendar.calendar_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Integer getCalendarSeq() {
        return calendarSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.calendar_seq
     *
     * @param calendarSeq the value for calendar.calendar_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setCalendarSeq(Integer calendarSeq) {
        this.calendarSeq = calendarSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.calendar_name
     *
     * @return the value of calendar.calendar_name
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getCalendarName() {
        return calendarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.calendar_name
     *
     * @param calendarName the value for calendar.calendar_name
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.group_seq
     *
     * @return the value of calendar.group_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Integer getGroupSeq() {
        return groupSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.group_seq
     *
     * @param groupSeq the value for calendar.group_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setGroupSeq(Integer groupSeq) {
        this.groupSeq = groupSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.removed
     *
     * @return the value of calendar.removed
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getRemoved() {
        return removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.removed
     *
     * @param removed the value for calendar.removed
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setRemoved(String removed) {
        this.removed = removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.reg_time
     *
     * @return the value of calendar.reg_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.reg_time
     *
     * @param regTime the value for calendar.reg_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.mod_time
     *
     * @return the value of calendar.mod_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.mod_time
     *
     * @param modTime the value for calendar.mod_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }
}