package org.ch.message.model;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Integer memberSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_id
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.passwd
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mobile
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.grade
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.removed
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String removed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.reg_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mod_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Date modTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_seq
     *
     * @return the value of member.member_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Integer getMemberSeq() {
        return memberSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_seq
     *
     * @param memberSeq the value for member.member_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setMemberSeq(Integer memberSeq) {
        this.memberSeq = memberSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_id
     *
     * @return the value of member.user_id
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_id
     *
     * @param userId the value for member.user_id
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.passwd
     *
     * @return the value of member.passwd
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.passwd
     *
     * @param passwd the value for member.passwd
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile
     *
     * @return the value of member.mobile
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile
     *
     * @param mobile the value for member.mobile
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.grade
     *
     * @return the value of member.grade
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.grade
     *
     * @param grade the value for member.grade
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.removed
     *
     * @return the value of member.removed
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getRemoved() {
        return removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.removed
     *
     * @param removed the value for member.removed
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setRemoved(String removed) {
        this.removed = removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.reg_time
     *
     * @return the value of member.reg_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.reg_time
     *
     * @param regTime the value for member.reg_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mod_time
     *
     * @return the value of member.mod_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mod_time
     *
     * @param modTime the value for member.mod_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }
}