package org.ch.message.model;

import java.util.Date;

public class Message {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.messasge_seq
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private Integer messasgeSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.message_type
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private String messageType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.sender
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private String sender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.state
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.reciever
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private String reciever;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.title
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.text
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private String text;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.result
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private String result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.reserved_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private Date reservedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.received_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private Integer receivedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.removed
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private String removed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.reg_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private Date regTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.mod_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	private Date modTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.messasge_seq
	 * @return  the value of message.messasge_seq
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public Integer getMessasgeSeq() {
		return messasgeSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.messasge_seq
	 * @param messasgeSeq  the value for message.messasge_seq
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setMessasgeSeq(Integer messasgeSeq) {
		this.messasgeSeq = messasgeSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.message_type
	 * @return  the value of message.message_type
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public String getMessageType() {
		return messageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.message_type
	 * @param messageType  the value for message.message_type
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.sender
	 * @return  the value of message.sender
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public String getSender() {
		return sender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.sender
	 * @param sender  the value for message.sender
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setSender(String sender) {
		this.sender = sender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.state
	 * @return  the value of message.state
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.state
	 * @param state  the value for message.state
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.reciever
	 * @return  the value of message.reciever
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public String getReciever() {
		return reciever;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.reciever
	 * @param reciever  the value for message.reciever
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setReciever(String reciever) {
		this.reciever = reciever;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.title
	 * @return  the value of message.title
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.title
	 * @param title  the value for message.title
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.text
	 * @return  the value of message.text
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.text
	 * @param text  the value for message.text
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.result
	 * @return  the value of message.result
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public String getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.result
	 * @param result  the value for message.result
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setResult(String result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.reserved_time
	 * @return  the value of message.reserved_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public Date getReservedTime() {
		return reservedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.reserved_time
	 * @param reservedTime  the value for message.reserved_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setReservedTime(Date reservedTime) {
		this.reservedTime = reservedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.received_time
	 * @return  the value of message.received_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public Integer getReceivedTime() {
		return receivedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.received_time
	 * @param receivedTime  the value for message.received_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setReceivedTime(Integer receivedTime) {
		this.receivedTime = receivedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.removed
	 * @return  the value of message.removed
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public String getRemoved() {
		return removed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.removed
	 * @param removed  the value for message.removed
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setRemoved(String removed) {
		this.removed = removed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.reg_time
	 * @return  the value of message.reg_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.reg_time
	 * @param regTime  the value for message.reg_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.mod_time
	 * @return  the value of message.mod_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public Date getModTime() {
		return modTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.mod_time
	 * @param modTime  the value for message.mod_time
	 * @mbg.generated  Tue Dec 18 11:12:01 KST 2018
	 */
	public void setModTime(Date modTime) {
		this.modTime = modTime;
	}
}