package org.ch.message.model;

import java.util.Date;

public class MGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_group.group_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Integer groupSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_group.group_name
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_group.removed
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private String removed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_group.reg_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_group.mod_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    private Date modTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_group.group_seq
     *
     * @return the value of m_group.group_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Integer getGroupSeq() {
        return groupSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_group.group_seq
     *
     * @param groupSeq the value for m_group.group_seq
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setGroupSeq(Integer groupSeq) {
        this.groupSeq = groupSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_group.group_name
     *
     * @return the value of m_group.group_name
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_group.group_name
     *
     * @param groupName the value for m_group.group_name
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_group.removed
     *
     * @return the value of m_group.removed
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public String getRemoved() {
        return removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_group.removed
     *
     * @param removed the value for m_group.removed
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setRemoved(String removed) {
        this.removed = removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_group.reg_time
     *
     * @return the value of m_group.reg_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_group.reg_time
     *
     * @param regTime the value for m_group.reg_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_group.mod_time
     *
     * @return the value of m_group.mod_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_group.mod_time
     *
     * @param modTime the value for m_group.mod_time
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }
}