package org.ch.message.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.ch.message.model.Calendar;

@Mapper
public interface CalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int deleteByPrimaryKey(Integer calendarSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int insert(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int insertSelective(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    Calendar selectByPrimaryKey(Integer calendarSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int updateByPrimaryKeySelective(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int updateByPrimaryKey(Calendar record);
}