package org.ch.message.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.ch.message.model.Member;

@Mapper
public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int deleteByPrimaryKey(Integer memberSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    Member selectByPrimaryKey(Integer memberSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Dec 17 12:03:26 KST 2018
     */
    int updateByPrimaryKey(Member record);
}