package org.ch.message.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.ch.message.model.Message;

@Mapper
public interface MessageMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated  Wed Dec 19 09:08:46 KST 2018
	 */
	int deleteByPrimaryKey(Integer messasgeSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated  Wed Dec 19 09:08:46 KST 2018
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated  Wed Dec 19 09:08:46 KST 2018
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated  Wed Dec 19 09:08:46 KST 2018
	 */
	Message selectByPrimaryKey(Integer messasgeSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated  Wed Dec 19 09:08:46 KST 2018
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated  Wed Dec 19 09:08:46 KST 2018
	 */
	int updateByPrimaryKey(Message record);

	List<Message> selectMessagesByState(int state);
}