package org.ch.message.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.ch.message.model.Schedule;

@Mapper
public interface ScheduleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_schedule
	 * @mbg.generated  Mon Dec 17 14:03:03 KST 2018
	 */
	int deleteByPrimaryKey(Integer scheduleSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_schedule
	 * @mbg.generated  Mon Dec 17 14:03:03 KST 2018
	 */
	int insert(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_schedule
	 * @mbg.generated  Mon Dec 17 14:03:03 KST 2018
	 */
	int insertSelective(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_schedule
	 * @mbg.generated  Mon Dec 17 14:03:03 KST 2018
	 */
	Schedule selectByPrimaryKey(Integer scheduleSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_schedule
	 * @mbg.generated  Mon Dec 17 14:03:03 KST 2018
	 */
	int updateByPrimaryKeySelective(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_schedule
	 * @mbg.generated  Mon Dec 17 14:03:03 KST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_schedule
	 * @mbg.generated  Mon Dec 17 14:03:03 KST 2018
	 */
	int updateByPrimaryKey(Schedule record);

	List<Schedule> selectSchedules(int beforeDay);
}